update to ES6 module syntax
I'm not an expert, but this resolved an issue when I was
using `vite:build` to precompile assest for a RoR app.

RollupError: "default" is not exported by "node_modules/@excid3/uppy-activestorage-upload/lib/index.js", imported by "app/javascript/controllers/image_upload_controller.js".